In [2]:
import sys, os
src_path = os.path.join('..', 'src')
if not src_path in sys.path:
    sys.path.insert(0, src_path)

In [3]:
from NumTForm import *
import tensorflow as tf
import numpy as np

In [4]:
test_in = tf.constant([[1, 2, 3]])

2022-04-27 08:18:41.600693: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
result = point_wise_feed_forward_network(3, 10)(test_in)
result

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.5620265 , -0.8509156 , -0.12096542]], dtype=float32)>

In [6]:
test_seq = tf.constant(
                [[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[3, 3, 3],
                  [4, 4, 4],
                  [5, 5, 5]]], dtype=tf.float32)

In [7]:
scaled_dot_product_attention(test_seq, test_seq, test_seq)

(<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[6.999908 , 7.9999084, 8.999908 ],
         [7.       , 8.       , 9.       ],
         [7.       , 8.       , 9.       ]],
 
        [[4.9944315, 4.9944315, 4.9944315],
         [4.999019 , 4.999019 , 4.999019 ],
         [4.999827 , 4.999827 , 4.999827 ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[9.4047004e-10, 3.0666615e-05, 9.9996936e-01],
         [2.7126563e-23, 5.2083069e-12, 1.0000000e+00],
         [7.8241341e-37, 8.8454476e-19, 1.0000000e+00]],
 
        [[3.0497726e-05, 5.5071679e-03, 9.9446231e-01],
         [9.5898793e-07, 9.7879942e-04, 9.9902022e-01],
         [3.0041676e-08, 1.7331065e-04, 9.9982673e-01]]], dtype=float32)>)

In [8]:
MultiHeadAttention(3, 3)(test_seq, test_seq, test_seq)

(<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[-2.6738546,  4.6390944, 13.825825 ],
         [-2.6748586,  4.6408362, 13.831016 ],
         [-2.6748586,  4.6408362, 13.831016 ]],
 
        [[-1.6668798,  2.892009 ,  8.619012 ],
         [-1.6745859,  2.9053795,  8.658859 ],
         [-1.6769805,  2.909534 ,  8.671241 ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
 array([[[[9.91156639e-07, 9.95070674e-04, 9.99003947e-01],
          [1.15192849e-15, 3.39399442e-08, 1.00000000e+00],
          [1.33743754e-24, 1.15646967e-12, 1.00000000e+00]],
 
         [[9.91156639e-07, 9.95070674e-04, 9.99003947e-01],
          [1.15192849e-15, 3.39399442e-08, 1.00000000e+00],
          [1.33743754e-24, 1.15646967e-12, 1.00000000e+00]],
 
         [[9.91156639e-07, 9.95070674e-04, 9.99003947e-01],
          [1.15192849e-15, 3.39399442e-08, 1.00000000e+00],
          [1.33743754e-24, 1.15646967e-12, 1.00000000e+00]]],
 
 
        [[[1.01699459e-03, 3.13697234

In [9]:
EncoderLayer(3, 3, 10)(test_seq, training=True)

(<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[-1.3821912 ,  0.95024586,  0.4319453 ],
         [-1.3836339 ,  0.9451277 ,  0.43850604],
         [-1.4141603 ,  0.6965271 ,  0.7176331 ]],
 
        [[ 0.87856483,  0.52045274, -1.3990176 ],
         [-1.3711785 ,  0.9854236 ,  0.38575482],
         [-0.37410212,  1.3681663 , -0.9940642 ]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
 array([[[[0.00493905, 0.06767858, 0.9273823 ],
          [0.00607994, 0.07475601, 0.919164  ],
          [0.00747631, 0.08248479, 0.9100388 ]],
 
         [[0.00493905, 0.06767858, 0.9273823 ],
          [0.00607994, 0.07475601, 0.919164  ],
          [0.00747631, 0.08248479, 0.9100388 ]],
 
         [[0.00493905, 0.06767858, 0.9273823 ],
          [0.00607994, 0.07475601, 0.919164  ],
          [0.00747631, 0.08248479, 0.9100388 ]]],
 
 
        [[[0.34544322, 0.3331884 , 0.32136834],
          [0.34950936, 0.33307576, 0.31741485],
          [0.35358924, 0.332931

In [10]:
Encoder(6, 3, 3, 10)(test_seq, training=True)

(<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
 array([[[-1.2419311 ,  0.03512952,  1.2068015 ],
         [ 0.31255922, -1.350737  ,  1.0381778 ],
         [ 0.43180805, -1.3821608 ,  0.9503528 ]],
 
        [[-0.18124884, -1.1240194 ,  1.3052683 ],
         [-0.11692926, -1.162086  ,  1.2790153 ],
         [-0.13822526, -1.1497674 ,  1.2879927 ]]], dtype=float32)>,
 {'encoder_layer1': <tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
  array([[[[2.2073741e-07, 5.8950729e-05, 9.9994087e-01],
           [3.9195196e-18, 8.6939535e-12, 1.0000000e+00],
           [5.0901969e-13, 1.5434392e-08, 1.0000000e+00]],
  
          [[2.2073741e-07, 5.8950729e-05, 9.9994087e-01],
           [3.9195196e-18, 8.6939535e-12, 1.0000000e+00],
           [5.0901969e-13, 1.5434392e-08, 1.0000000e+00]],
  
          [[2.2073741e-07, 5.8950729e-05, 9.9994087e-01],
           [3.9195196e-18, 8.6939535e-12, 1.0000000e+00],
           [5.0901969e-13, 1.5434392e-08, 1.0000000e+00]]],
  
  
         [[[1.

In [11]:
Transformer(6, 3, 3, 10)(test_seq)

(<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[-2.476782],
        [-1.407672]], dtype=float32)>,
 {'encoder_layer1': <tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
  array([[[[0.42128378, 0.32617632, 0.2525399 ],
           [0.6552329 , 0.24964894, 0.09511822],
           [0.81789565, 0.15335163, 0.02875271]],
  
          [[0.42128378, 0.32617632, 0.2525399 ],
           [0.6552329 , 0.24964894, 0.09511822],
           [0.81789565, 0.15335163, 0.02875271]],
  
          [[0.42128378, 0.32617632, 0.2525399 ],
           [0.6552329 , 0.24964894, 0.09511822],
           [0.81789565, 0.15335163, 0.02875271]]],
  
  
         [[[0.4144545 , 0.32721183, 0.25833368],
           [0.44206157, 0.3225663 , 0.23537214],
           [0.46965444, 0.31673694, 0.21360865]],
  
          [[0.4144545 , 0.32721183, 0.25833368],
           [0.44206157, 0.3225663 , 0.23537214],
           [0.46965444, 0.31673694, 0.21360865]],
  
          [[0.4144545 , 0.32721183, 0.25833368],
         